### ISSUE TITLE
provide a compiled version

### ISSUE THREAD

**Issue by b2un0** [johnwoo-nl/emproto#2]
I have now spent several hours trying to use your code in a nodejs project, which can then run in a simple docker container.
However, it is somehow impossible for me to compile the typescript code cleanly.

the "installation" guide you provided in your README.md does not work for me.

maybe you can publish a simple npm package directly here in github?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

https://github.com/actions/typescript-action

**Comment by johnwoo-nl** [comment]
Yes, I developed and use the library in a pure Typescript environment, without transpiling.
Of course it should be usable in JS projects as well, either by having configuration to be transpilable by the parent project's toolchain, or have a prebuilt JS version in the npm package, with TS type mappings for TS projects. I'll setup a local project in JS to get this done (but it may take some time).

**Comment by johnwoo-nl** [comment]
Alright, I took some time to make the library buildable using tsc, and usable in JS projects. The readme installation section is updated with how to build (just `npm run build`, really).

I'll look into creating an npm package from the built library later on -- I'd prefer to have it a bit more stable/clean/functional before publishing it as a package. I uploaded the code because I had it working locally, reading and controlling my wallbox, and thought it could be useful already (even if not production-worthy) since you asked about the status ;)

**Comment by b2un0** [comment]
> since you asked about the status ;)

You are absolutely right and I am very grateful to you.

I hadn't actually expected typescript.

I come from the vanilla javascript world and still program everything natively with ES6.

but thank you for your effort and i'll keep trying.


*edit*

thank you very much!

now it works mit ES6 💯
